#pragma once

// Name: P, Version: 1


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.AnimGraph
struct UFP_Vampire_Skeleton_AnimBlueprint_C_AnimGraph_Params
{
	struct FPoseLink                                   AnimGraph;                                                 // 0x0000(0x0010)  (Parm, OutParm, NoDestructor)
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_68B4473744AC5E7A37913EB8A7FC1282
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_68B4473744AC5E7A37913EB8A7FC1282_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_5E04F4AD4233D6B7C6781E8807389A82
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_5E04F4AD4233D6B7C6781E8807389A82_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_0626F8F24AE7BE78B4CF609861EC2DBF
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_0626F8F24AE7BE78B4CF609861EC2DBF_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_7F7E851349742C9DB16019B4F283556D
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_7F7E851349742C9DB16019B4F283556D_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_BlendListByBool_6F93BBDB48A08F69E58F809912031B15
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_BlendListByBool_6F93BBDB48A08F69E58F809912031B15_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_6F6C24254D6653C3850F5F9475BE1FF8
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_6F6C24254D6653C3850F5F9475BE1FF8_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_E592B28A48CF899973AC9D9A838B28C9
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_E592B28A48CF899973AC9D9A838B28C9_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_27CB73B240D080105F994882CD484350
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_27CB73B240D080105F994882CD484350_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_3F0B6D574A0A8898AC51F18F24F8D473
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_3F0B6D574A0A8898AC51F18F24F8D473_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_5A8C93784A25E4B957A94EB1E77BD818
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_5A8C93784A25E4B957A94EB1E77BD818_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_E96A05B4459E8EF167721BA4EE0EAB5B
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_E96A05B4459E8EF167721BA4EE0EAB5B_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_43835B1E425CB74A2EF7228208EA720C
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_43835B1E425CB74A2EF7228208EA720C_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_CFE9FC224AE3A508A08200B5091906B6
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_CFE9FC224AE3A508A08200B5091906B6_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_B3658EF247941C44F15DC49961744327
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_B3658EF247941C44F15DC49961744327_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_CDAEDA2E4933624A6C9BCF910BA5838A
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_CDAEDA2E4933624A6C9BCF910BA5838A_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_981581A4499549D4DBDD57B029239D0B
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_981581A4499549D4DBDD57B029239D0B_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_EDDD52D74FE7EFE93FF4978E8E5F7CD0
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_EDDD52D74FE7EFE93FF4978E8E5F7CD0_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_FC7E19174D19009E5F9DCDA8B0208DCF
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_FC7E19174D19009E5F9DCDA8B0208DCF_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_BD635E2444F2086E75FC26A418C2E4E9
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_BD635E2444F2086E75FC26A418C2E4E9_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_05878C17498F7DA5BFE3F69BE8C66240
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_05878C17498F7DA5BFE3F69BE8C66240_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_2531E8E2448E191987FB1783E52D0128
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_2531E8E2448E191987FB1783E52D0128_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_C9C9BEED4991BA02FA6781A43A688AA2
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_C9C9BEED4991BA02FA6781A43A688AA2_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_29C9DB414333F1C4E96DC5A6838C8F4E
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_29C9DB414333F1C4E96DC5A6838C8F4E_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_503E3540482D7AAF3BFD49B977E632C7
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_503E3540482D7AAF3BFD49B977E632C7_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_2916D70D488EB4AAC2B3FBB0FE6DEA20
struct UFP_Vampire_Skeleton_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_AnimGraphNode_TransitionResult_2916D70D488EB4AAC2B3FBB0FE6DEA20_Params
{
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.BlueprintUpdateAnimation
struct UFP_Vampire_Skeleton_AnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                                // 0x0000(0x0004)  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function FP_Vampire_Skeleton_AnimBlueprint.FP_Vampire_Skeleton_AnimBlueprint_C.ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint
struct UFP_Vampire_Skeleton_AnimBlueprint_C_ExecuteUbergraph_FP_Vampire_Skeleton_AnimBlueprint_Params
{
	int                                                EntryPoint;                                                // 0x0000(0x0004)  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
